//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// nFTDServer.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NFTDSERVER_DIALOG           102
#define IDS_NEW_FOLDER                  102
#define IDS_TRANSFER_START              103
#define IDS_REG_HKEY_LOCAL_MACH         104
#define IDS_REG_PROXYINFO               105
#define NFTD_IDS_AGENT                  106
#define NFTD_IDS_REMOTE_PC              107
#define NFTD_IDS_COMPUTER               108
#define NFTD_IDS_DESKTOP                109
#define NFTD_IDS_DOCUMENT               110
#define NFTD_IDS_CONFIG                 111
#define NFTD_IDS_CONFIG_FAVORITE        112
#define NFTD_IDS_CONFIG_PATH            113
#define NFTD_IDS_ROOT                   114
#define IDS_REG_HKEY_LOCAL_MACH_ANYSUPPORT 115
#define NFTD_IDS_SEND                   116
#define NFTD_IDS_RECV                   117
#define IDS_HOST_PC                     118
#define IDS_SUPPORTER_PC                119
#define IDS_TEXT_TITLE                  120
#define IDS_TEXT_TITLE2                 121
#define IDS_EXIST_FOLDER                122
#define IDS_REG_HKEY_LOCAL_MACH_LINKVNC 123
#define IDS_TEXT_LINKVNC                124
#define IDS_TEXT_LINKEIGHT              125
#define IDS_REG_HKEY_LOCAL_MACH_LINKEIGHT 126
#define IDS_COOPY_PATH                  127
#define IDR_MAINFRAME                   128
#define IDS_INPUT_FOLDER                128
#define IDS_NOT_EXIST_PATH              129
#define IDS_COPY_PATH_FAIL              130
#define IDD_FILETRANSFER                130
#define IDS_CLOSE_AFTER_TRANSFER        131
#define IDS_FOLDER                      132
#define IDD_MESSAGE                     132
#define IDS_PATH                        133
#define IDS_DEVICE_NAME                 134
#define IDR_MENU_TREE_CONTEXT           134
#define IDS_TRANSFER                    135
#define IDR_MENU_TREE_CONTEXT1          135
#define IDR_MENU_LIST_CONTEXT           135
#define IDD_EXIST_FILE                  135
#define IDS_DISCONNECT                  136
#define IDS_FONT                        137
#define NFTD_IDS_CONNECTING_P2P         138
#define NFTD_IDS_CONNECTING_AP2P        139
#define NFTD_ISD_FOLDER_FILE_LIST_LOADING 140
#define IDS_EXIST_SRC_FILE_TITLE        141
#define IDS_EXIST_DST_FILE_TITLE        142
#define IDS_DISABLE_SUCCEED_TRANSFER    143
#define IDS_REFRESH                     144
#define IDS_OPEN                        145
#define IDS_DELETE                      146
#define IDS_SELECT_ALL                  147
#define IDS_RENAME                      148
#define IDS_PROPERTY                    149
#define IDB_LEFT_ARROW                  149
#define IDS_ITEM_COUNT                  150
#define IDB_LOCAL_PC                    150
#define IDS_ITEM_SELECTED_COUNT         151
#define IDB_LOCAL_PC1                   151
#define IDS_FILE_LAST_MODIFIED_TIME     152
#define IDB_DRAG_MULTI_FILES            152
#define IDS_FILE_SIZE                   153
#define IDB_REMOTE_PC                   153
#define IDB_REMOTE_PC1                  154
#define IDS_FAVORITE                    154
#define IDB_RIGHT_ARROW                 155
#define IDS_SET                         155
#define IDB_DRAG_SINGLE_FILE            156
#define IDS_RESET                       156
#define IDB_ARROW_LEFT_TO_RIGHT         157
#define IDS_ADD                         157
#define IDB_ARROW_RIGHT_TO_LEFT         158
#define IDS_REMOVE                      158
#define IDS_FAVORITE_ADD                159
#define IDR_MENU_FAVORITE_CONTEXT       159
#define IDS_FAVORITE_REMOVE             160
#define IDS_LARGER_FILE_SIZE            161
#define IDS_CONNECT_FAIL_NO_RESPONSE    162
#define IDS_EQUAL_FILE_SIZE             163
#define IDS_SHOW_ON_REMOTE              164
#define IDS_OPEN_WITH_EXPLORER          165
#define IDS_SRC_DST_SAME_PATH           166
#define IDS_CLOSE_ALL_TRANSFER_SUCCESS  167
#define IDC_TREE_LOCAL                  1000
#define IDC_LIST_LOCAL                  1001
#define IDC_TREE_REMOTE                 1002
#define IDC_LIST_REMOTE                 1003
#define IDC_PATH_LOCAL                  1004
#define IDC_PATH_REMOTE                 1005
#define IDC_SPLITTER_CENTER             1006
#define IDC_SPLITTER_LEFT               1007
#define IDC_SPLITTER_RIGHT              1008
#define IDC_STATIC_COUNT_LOCAL          1009
#define IDC_STATIC_COUNT_REMOTE         1010
#define IDC_PROGRESS_SPACE_LOCAL        1011
#define IDC_STATIC_LOCAL_DISK_SPACE     1011
#define IDC_PROGRESS_SPACE_REMOTE       1012
#define IDC_PROGRESS                    1012
#define IDC_STATIC_REMOTE_DISK_SPACE    1012
#define IDC_BUTTON_CANCEL               1013
#define IDC_SPLITTER_CENTER2            1013
#define IDC_LIST                        1014
#define IDC_LIST_LOCAL_FAVORITE         1014
#define IDC_STATIC_MESSAGE              1015
#define IDC_LIST_REMOTE_FAVORITE        1015
#define IDC_STATIC_SPEED                1016
#define IDC_STATIC_SRC_FILE_TITLE       1016
#define IDC_SPLITTER_LOCAL_FAVORITE     1016
#define IDC_STATIC_INDEX                1017
#define IDC_STATIC_DST_FILE_TITLE       1017
#define IDC_SPLITTER_REMOTE_FAVORITE    1017
#define IDC_LIST1                       1018
#define IDC_LIST_QUEUE                  1018
#define IDC_STATIC_SRC_FILE             1018
#define IDC_STATIC_DST_FILE             1019
#define IDC_RADIO_SUCCEED               1020
#define IDC_RADIO_OVERWRITE             1021
#define IDC_RADIO_SKIP                  1022
#define IDC_CHECK_APPLY_ALL             1023
#define IDC_STATIC_SRC_FILESIZE         1024
#define IDC_STATIC_INDEX_BYTES          1024
#define IDC_STATIC_REMAIN_SPEED         1025
#define IDC_STATIC_DST_MTIME            1025
#define IDC_STATIC_SRC_MTIME            1026
#define IDC_STATIC_LOCAL                1026
#define IDC_STATIC_REMOTE               1027
#define IDC_STATIC_DST_FILESIZE         1028
#define IDC_CHECK_CLOSE_AFTER_ALL       1028
#define IDC_BUTTON_LOCAL_TO_REMOTE      1029
#define IDC_BUTTON_REMOTE_TO_LOCAL      1030
#define IDC_SLIDER_LOCAL_DISK_SPACE     1031
#define IDC_SLIDER_REMOTE_DISK_SPACE    1032
#define NFTD_IDS_MSGBOX_TITLE           2032
#define NFTD_IDS_MSGBOX_RUN_1           2033
#define NFTD_IDS_MSGBOX_RUN_2           2034
#define NFTD_IDS_MSGBOX_ALREADYRUN      2035
#define NFTD_IDS_MSGBOX_ACCESSDENY      2036
#define NFTD_IDS_MSGBOX_MAKEFOLDERFAIL  2037
#define NFTD_IDS_MSGBOX_DISKFULL        2038
#define NFTD_IDS_MSGBOX_DELETE          2039
#define NFTD_IDS_MSGBOX_DELETE_TITLE    2040
#define NFTD_IDS_MSGBOX_DELETEFAIL      2041
#define NFTD_IDS_MSGBOX_CANCELTRANSFER  2042
#define NFTD_IDS_INFO_MUTEXNAME         2043
#define NFTD_IDS_LISTCTRL_NAME          2044
#define NFTD_IDS_LISTCTRL_SIZE          2045
#define NFTD_IDS_LISTCTRL_DATE          2046
#define NFTD_IDS_LISTCTRL_STATUS        2047
#define NFTD_IDS_LISTCTRL_FROM          2048
#define NFTD_IDS_LISTCTRL_TO            2049
#define NFTD_IDS_SPACE                  2050
#define NFTD_IDS_TRANSFER_INIT          2051
#define NFTD_IDS_TRANSFER_FAIL          2052
#define NFTD_IDS_TRANSFER_TRANS         2053
#define NFTD_IDS_TRANSFER_COMPLETE      2054
#define NFTD_IDS_COMPLETE               2055
#define NFTD_IDS_FAIL                   2056
#define NFTD_IDS_CLOSE                  2057
#define NFTD_IDS_TRANSFER_FILE          2058
#define NFTD_IDS_TRANSFER_LEFT          2059
#define NFTD_IDS_TRANSFER_SPEED         2060
#define NFTD_IDS_FREESPACE              2061
#define NFTD_IDS_TOTALSPACE             2062
#define NFTD_IDS_CANCEL                 2063
#define NFTD_IDS_MSGBOX_TITLEOVERLAPPING 2064
#define NFTD_IDS_OK                     2065
#define IDS_CONFIRM_EXIT                2079
#define NFTD_IDS_TRANSFER_FAIL_MSG      2080
#define NFTD_IDS_SELECT_FILE            2081
#define NFTD_IDS_EXIST_FILE             2082
#define NFTD_IDS_SIZE                   2083
#define NFTD_IDS_CONTINUE               2084
#define NFTD_IDS_OVERWRITE              2085
#define NFTD_IDS_PASS                   2086
#define NFTD_IDS_CHECK_ALL              2087
#define ID_LIST_32771                   32771
#define ID_LIST_32772                   32772
#define ID_LIST_32773                   32773
#define ID_LIST_32774                   32774
#define ID_LIST_32775                   32775
#define ID_LIST_32776                   32776
#define ID_LIST_CONTEXT_MENU_SEND       32777
#define ID_LIST_CONTEXT_MENU_NEW_FOLDER 32778
#define ID_LIST_CONTEXT_MENU_RENAME     32779
#define ID_LIST_CONTEXT_MENU_DELETE     32780
#define ID_LIST_CONTEXT_MENU_REFRESH    32781
#define ID_LIST_CONTEXT_MENU_SELECT_ALL 32782
#define ID_LIST_32783                   32783
#define ID_LIST_32784                   32784
#define ID_LIST_CONTEXT_MENU_OPEN       32785
#define ID_LIST_CONTEXT_MENU_PROPERTY   32786
#define ID_LIST_CONTEXT_MENU_OPEN_EXPLORER 32787
#define ID_LIST_32788                   32788
#define ID_LIST_CONTEXT_MENU_FAVORITE   32789
#define ID_FAVORITE_32790               32790
#define ID_FAVORITE_CONTEXT_MENU_DELETE 32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
